#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.16
# In conjunction with Tcl version 8.6
#    Oct 10, 2018 01:37:58 PM -0300  platform: Windows NT

import sys, pymysql

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

valor = 0
class Application(Tk):
    def __init__(self):
        Tk.__init__(self)
        self.frame = TheMat_Restaurante(self)
        self.frame.pack()

    def change(self, frame):
        self.frame.pack_forget()
        self.frame = frame(self)
        self.frame.pack()

class TheMat_Restaurante(Frame):
    def __init__(self, master=None, **kwargs):
        Frame.__init__(self, master, **kwargs)
        def login():
            connection = pymysql.connect(host='us-cdbr-iron-east-01.cleardb.net', user='bfd18cb29ee411', password='903f4c99', db='heroku_efb1a162a601666', charset='utf8mb4', cursorclass=pymysql.cursors.DictCursor)
            try:
                with connection.cursor() as cursor:
                    sql = "SELECT `user`, `pass` FROM `restaurante` WHERE `user`=%s AND `pass`=%s"
                    cursor.execute(sql, (self.user1.get(), self.senha1.get(),))
                    result = cursor.fetchone()
                    user = self.user1.get()
                    senha = self.senha1.get()
                    if user == "" or senha == "":
                        print("Usuário ou Senha Incorreta!")
                    elif result:

                        self.master.change(TheMat_Restaurante2)
                        self.Button1.destroy()
                        self.senhax.destroy()
                        self.user.destroy()
                        self.senha1.destroy()
                        self.user1.destroy()
                    else:  
                        print("Usuário ou Senha Incorreta!")
            except TypeError:
                print("Usuário ou Senha Incorreta!")
            sys.stdout.flush()

        '''This class configures and populates thetoplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 

        master.geometry("372x195+554+164")
        master.title("TheMat Restaurante")
        master.configure(background="#63051e")



        self.Button1 = Button(master)
        self.Button1.place(relx=0.27, rely=0.72, height=34, width=167)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#4e9cd8")
        self.Button1.configure(command=login)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Login''')
        self.Button1.configure(width=167)

        self.user = Label(master)
        self.user.place(relx=0.05, rely=0.1, height=21, width=144)
        self.user.configure(background="#4e9cd8")
        self.user.configure(disabledforeground="#a3a3a3")
        self.user.configure(foreground="#000000")
        self.user.configure(text='''User''')
        self.user.configure(width=144)

        self.senhax = Label(master)
        self.senhax.place(relx=0.05, rely=0.41, height=21, width=144)
        self.senhax.configure(activebackground="#f9f9f9")
        self.senhax.configure(activeforeground="black")
        self.senhax.configure(background="#4e9cd8")
        self.senhax.configure(disabledforeground="#a3a3a3")
        self.senhax.configure(foreground="#000000")
        self.senhax.configure(highlightbackground="#d9d9d9")
        self.senhax.configure(highlightcolor="black")
        self.senhax.configure(text='''Pass''')
        self.senhax.configure(width=144)

        self.user1 = Entry(master)
        self.user1.place(relx=0.48, rely=0.1,height=20, relwidth=0.47)
        self.user1.configure(background="#6960bf")
        self.user1.configure(disabledforeground="#a3a3a3")
        self.user1.configure(font="TkFixedFont")
        self.user1.configure(foreground="#000000")
        self.user1.configure(insertbackground="black")
        self.user1.configure(width=174)

        self.senha1 = Entry(master)
        self.senha1.place(relx=0.48, rely=0.41,height=20, relwidth=0.47)
        self.senha1.configure(background="#6960bf")
        self.senha1.configure(disabledforeground="#a3a3a3")
        self.senha1.configure(font="TkFixedFont")
        self.senha1.configure(foreground="#000000")
        self.senha1.configure(show = '*')
        self.senha1.configure(highlightbackground="#d9d9d9")
        self.senha1.configure(highlightcolor="black")
        self.senha1.configure(insertbackground="black")
        self.senha1.configure(selectbackground="#c4c4c4")
        self.senha1.configure(selectforeground="black")

        self.menubar = Menu(master,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        master.configure(menu = self.menubar)

class TheMat_Restaurante2(Frame):
    def __init__(self, master=None, **kwargs):
        Frame.__init__(self, master, **kwargs)

        def agua():
            global valor
            print('agua')
            valor = valor + 2
            sys.stdout.flush()

        def cerveja():
            global valor
            print('cerveja')
            valor = valor + 7
            sys.stdout.flush()

        def cerveja2():
            global valor
            print('cerveja2')
            valor = valor + 9
            sys.stdout.flush()

        def coca():
            global valor
            print('coca')
            valor = valor + 6
            sys.stdout.flush()

        def fechar():
            global valor
            print(valor)
            self.master.change(Soma_TheMat)
            self.coca.destroy()
            self.cerveja2.destroy()
            self.cerveja.destroy()
            self.fechar.destroy()
            self.macarrao.destroy()
            self.agua.destroy()
            self.parmegiana.destroy()
            self.pizza.destroy()
            self.redbull.destroy()
            self.sanduba.destroy()
            self.vodka.destroy()
            self.bebidas.destroy()
            self.bebidas_6.destroy()
            sys.stdout.flush()

        def macarrao():
            global valor
            print('macarrao')
            valor = valor + 15
            sys.stdout.flush()

        def parmegiana():
            global valor
            print('parmegiana')
            valor = valor + 25
            sys.stdout.flush()

        def pizza():
            global valor
            print('pizza')
            valor = valor + 30
            sys.stdout.flush()

        def redbull():
            global valor
            print('redbull')
            valor = valor + 10
            sys.stdout.flush()

        def sanduba():
            global valor
            print('sanduba')
            valor = valor + 7
            sys.stdout.flush()

        def vodka():
            global valor
            print('vodka')
            valor = valor + 50
            sys.stdout.flush()
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Sitka Banner} -size 15 -weight normal -slant"  \
            " roman -underline 0 -overstrike 0"

        master.geometry("368x322+508+183")
        master.title("TheMat Restaurante")
        master.configure(background="#a57dd8")
        master.configure(highlightbackground="#d9d9d9")
        master.configure(highlightcolor="black")



        self.agua = Button(master)
        self.agua.place(relx=0.03, rely=0.12, height=24, width=157)
        self.agua.configure(activebackground="#d9d9d9")
        self.agua.configure(activeforeground="#000000")
        self.agua.configure(background="#e351e8")
        self.agua.configure(command=agua)
        self.agua.configure(disabledforeground="#a3a3a3")
        self.agua.configure(foreground="#000000")
        self.agua.configure(highlightbackground="#d9d9d9")
        self.agua.configure(highlightcolor="black")
        self.agua.configure(pady="0")
        self.agua.configure(text='''Água - 2 R$''')

        self.bebidas = Label(master)
        self.bebidas.place(relx=0.24, rely=0.03, height=21, width=164)
        self.bebidas.configure(activebackground="#a57dd8")
        self.bebidas.configure(activeforeground="black")
        self.bebidas.configure(background="#a57dd8")
        self.bebidas.configure(disabledforeground="#a3a3a3")
        self.bebidas.configure(font=font9)
        self.bebidas.configure(foreground="#000000")
        self.bebidas.configure(highlightbackground="#d9d9d9")
        self.bebidas.configure(highlightcolor="black")
        self.bebidas.configure(text='''Bebidas:''')

        self.coca = Button(master)
        self.coca.place(relx=0.52, rely=0.12, height=24, width=157)
        self.coca.configure(activebackground="#d9d9d9")
        self.coca.configure(activeforeground="#000000")
        self.coca.configure(background="#e351e8")
        self.coca.configure(command=coca)
        self.coca.configure(disabledforeground="#a3a3a3")
        self.coca.configure(foreground="#000000")
        self.coca.configure(highlightbackground="#d9d9d9")
        self.coca.configure(highlightcolor="black")
        self.coca.configure(pady="0")
        self.coca.configure(text='''Coca-Cola Lata - 6 R$''')

        self.redbull = Button(master)
        self.redbull.place(relx=0.03, rely=0.37, height=24, width=157)
        self.redbull.configure(activebackground="#d9d9d9")
        self.redbull.configure(activeforeground="#000000")
        self.redbull.configure(background="#e351e8")
        self.redbull.configure(command=redbull)
        self.redbull.configure(disabledforeground="#a3a3a3")
        self.redbull.configure(foreground="#000000")
        self.redbull.configure(highlightbackground="#d9d9d9")
        self.redbull.configure(highlightcolor="black")
        self.redbull.configure(pady="0")
        self.redbull.configure(text='''RedBull Lata - 10 R$''')

        self.vodka = Button(master)
        self.vodka.place(relx=0.52, rely=0.37, height=24, width=157)
        self.vodka.configure(activebackground="#d9d9d9")
        self.vodka.configure(activeforeground="#000000")
        self.vodka.configure(background="#e351e8")
        self.vodka.configure(command=vodka)
        self.vodka.configure(disabledforeground="#a3a3a3")
        self.vodka.configure(foreground="#000000")
        self.vodka.configure(highlightbackground="#d9d9d9")
        self.vodka.configure(highlightcolor="black")
        self.vodka.configure(pady="0")
        self.vodka.configure(text='''Vodka - 50 R$''')

        self.cerveja2 = Button(master)
        self.cerveja2.place(relx=0.52, rely=0.25, height=24, width=157)
        self.cerveja2.configure(activebackground="#d9d9d9")
        self.cerveja2.configure(activeforeground="#000000")
        self.cerveja2.configure(background="#e351e8")
        self.cerveja2.configure(command=cerveja2)
        self.cerveja2.configure(disabledforeground="#a3a3a3")
        self.cerveja2.configure(foreground="#000000")
        self.cerveja2.configure(highlightbackground="#d9d9d9")
        self.cerveja2.configure(highlightcolor="black")
        self.cerveja2.configure(pady="0")
        self.cerveja2.configure(text='''Cerveja Original - 9 R$''')

        self.cerveja = Button(master)
        self.cerveja.place(relx=0.03, rely=0.25, height=24, width=157)
        self.cerveja.configure(activebackground="#d9d9d9")
        self.cerveja.configure(activeforeground="#000000")
        self.cerveja.configure(background="#e351e8")
        self.cerveja.configure(command=cerveja)
        self.cerveja.configure(disabledforeground="#a3a3a3")
        self.cerveja.configure(foreground="#000000")
        self.cerveja.configure(highlightbackground="#d9d9d9")
        self.cerveja.configure(highlightcolor="black")
        self.cerveja.configure(pady="0")
        self.cerveja.configure(text='''Cerveja Tradicional - 7 R$''')

        self.bebidas_6 = Label(master)
        self.bebidas_6.place(relx=0.24, rely=0.53, height=21, width=164)
        self.bebidas_6.configure(activebackground="#a57dd8")
        self.bebidas_6.configure(activeforeground="black")
        self.bebidas_6.configure(background="#a57dd8")
        self.bebidas_6.configure(disabledforeground="#a3a3a3")
        self.bebidas_6.configure(font=font9)
        self.bebidas_6.configure(foreground="#000000")
        self.bebidas_6.configure(highlightbackground="#d9d9d9")
        self.bebidas_6.configure(highlightcolor="black")
        self.bebidas_6.configure(text='''Comidas:''')

        self.parmegiana = Button(master)
        self.parmegiana.place(relx=0.03, rely=0.78, height=24, width=157)
        self.parmegiana.configure(activebackground="#d9d9d9")
        self.parmegiana.configure(activeforeground="#000000")
        self.parmegiana.configure(background="#e351e8")
        self.parmegiana.configure(command=parmegiana)
        self.parmegiana.configure(disabledforeground="#a3a3a3")
        self.parmegiana.configure(foreground="#000000")
        self.parmegiana.configure(highlightbackground="#d9d9d9")
        self.parmegiana.configure(highlightcolor="black")
        self.parmegiana.configure(pady="0")
        self.parmegiana.configure(text='''Parmegiana - 25R$''')

        self.pizza = Button(master)
        self.pizza.place(relx=0.52, rely=0.78, height=24, width=157)
        self.pizza.configure(activebackground="#d9d9d9")
        self.pizza.configure(activeforeground="#000000")
        self.pizza.configure(background="#e351e8")
        self.pizza.configure(command=pizza)
        self.pizza.configure(disabledforeground="#a3a3a3")
        self.pizza.configure(foreground="#000000")
        self.pizza.configure(highlightbackground="#d9d9d9")
        self.pizza.configure(highlightcolor="black")
        self.pizza.configure(pady="0")
        self.pizza.configure(text='''Pizza - 30 R$''')

        self.sanduba = Button(master)
        self.sanduba.place(relx=0.03, rely=0.65, height=24, width=157)
        self.sanduba.configure(activebackground="#d9d9d9")
        self.sanduba.configure(activeforeground="#000000")
        self.sanduba.configure(background="#e351e8")
        self.sanduba.configure(command=sanduba)
        self.sanduba.configure(disabledforeground="#a3a3a3")
        self.sanduba.configure(foreground="#000000")
        self.sanduba.configure(highlightbackground="#d9d9d9")
        self.sanduba.configure(highlightcolor="black")
        self.sanduba.configure(pady="0")
        self.sanduba.configure(text='''Sanduiche  - 7 R$''')

        self.macarrao = Button(master)
        self.macarrao.place(relx=0.52, rely=0.65, height=24, width=157)
        self.macarrao.configure(activebackground="#d9d9d9")
        self.macarrao.configure(activeforeground="#000000")
        self.macarrao.configure(background="#e351e8")
        self.macarrao.configure(command=macarrao)
        self.macarrao.configure(disabledforeground="#a3a3a3")
        self.macarrao.configure(foreground="#000000")
        self.macarrao.configure(highlightbackground="#d9d9d9")
        self.macarrao.configure(highlightcolor="black")
        self.macarrao.configure(pady="0")
        self.macarrao.configure(text='''Macarronada - 15 R$''')

        self.fechar = Button(master)
        self.fechar.place(relx=0.27, rely=0.9, height=24, width=147)
        self.fechar.configure(activebackground="#d9d9d9")
        self.fechar.configure(activeforeground="#000000")
        self.fechar.configure(background="#d8a0c2")
        self.fechar.configure(command=fechar)
        self.fechar.configure(disabledforeground="#a3a3a3")
        self.fechar.configure(foreground="#000000")
        self.fechar.configure(highlightbackground="#d9d9d9")
        self.fechar.configure(highlightcolor="black")
        self.fechar.configure(pady="0")
        self.fechar.configure(text='''Fechar Conta''')

class Soma_TheMat(Frame):
    def __init__(self, master=None, valor=0, **kwargs):
        Frame.__init__(self, master, **kwargs)
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Sitka Subheading} -size 12 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI Historic} -size 17 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"

        master.geometry("254x178+581+227")
        master.title("Soma TheMat")
        master.configure(background="#948cd8")



        self.pagar = Label(master)
        self.pagar.place(relx=0.12, rely=0.11, height=41, width=194)
        self.pagar.configure(background="#948cd8")
        self.pagar.configure(disabledforeground="#a3a3a3")
        self.pagar.configure(font=font10)
        self.pagar.configure(foreground="#000000")
        self.pagar.configure(text='''Valor a Ser Pago:''')
        self.pagar.configure(width=194)

        self.money = Label(master)
        self.money.place(relx=0.31, rely=0.39, height=91, width=94)
        self.money.configure(background="#948cd8")
        self.money.configure(disabledforeground="#a3a3a3")
        self.money.configure(font=font9)
        self.money.configure(foreground="#000000")
        self.money.configure(text=valor)
        self.money.configure(width=94)






if __name__=="__main__":
    app=Application()
    app.mainloop()



